version: '3.7'
services:
  speedtest:
    image: payback159/stm:latest
    restart: always
    env_file:
     - './speedtest.env'
    links:
     - influxdb

  grafana:
    image: grafana/grafana:6.7.3-ubuntu
    ports:
     - "80:3000"
     - "443:3000"
    restart: always
    volumes:
     - ".grafana-data:/var/lib/grafana"
    env_file:
     - './grafana.env'
    links:
     - influxdb

  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'influx.env'
    volumes:
      - ".influx-data:/var/lib/influxdb"
