name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'speedtest-app/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'speedtest-app/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./speedtest-app --file ./Dockerfile --tag payback159/stm:$(date +%s)
